export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST"
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE"

export const GET_ALL_CART_PRODUCT_REQUEST = "GET_ALL_CART_PRODUCT_REQUEST"
export const GET_ALL_CART_PRODUCT_SUCCESS = "GET_ALL_CART_PRODUCT_SUCCESS"
export const GET_ALL_CART_PRODUCT_FAILURE = "GET_ALL_CART_PRODUCT_FAILURE"